SELECT 
m_peg.id_opd AS id_opd,
count(m_peg.id_opd) AS jum_peg_all,
count(if (m_peg.status_peg=0, 1, null)) AS jum_peg_ta,
count(if (m_peg.status_peg=1, 1, null)) AS jum_peg_pns,
count(if (m_peg.status_peg=2, 1, null)) AS jum_peg_cpns,
count(if (m_peg.status_peg=3, 1, null)) AS jum_peg_ptt,
count(if (m_peg.status_peg=4, 1, null)) AS jum_peg_os,
count(if (m_peg.status_peg=5, 1, null)) AS jum_peg_pkl,
count(if (m_peg.jk='L', 1, null)) AS jum_peg_laki,
count(if (m_peg.jk='P', 1, null)) AS jum_peg_perempuan,
count(if (m_peg.agama=1, 1, null)) AS jum_peg_islam,
count(if (m_peg.agama=2, 1, null)) AS jum_peg_kristen,
count(if (m_peg.agama=3, 1, null)) AS jum_peg_protestan,
count(if (m_peg.agama=4, 1, null)) AS jum_peg_hindu,
count(if (m_peg.agama=5, 1, null)) AS jum_peg_budha,
count(if (m_peg.agama=6, 1, null)) AS jum_peg_konghuchu,
count(if (m_peg.gol_ruang='1a', 1, null)) AS jum_peg_gol_1a,
count(if (m_peg.gol_ruang='1b', 1, null)) AS jum_peg_gol_1b,
count(if (m_peg.gol_ruang='1c', 1, null)) AS jum_peg_gol_1c,
count(if (m_peg.gol_ruang='1d', 1, null)) AS jum_peg_gol_1d,
count(if (m_peg.gol_ruang='2a', 1, null)) AS jum_peg_gol_2a,
count(if (m_peg.gol_ruang='2b', 1, null)) AS jum_peg_gol_2b,
count(if (m_peg.gol_ruang='2c', 1, null)) AS jum_peg_gol_2c,
count(if (m_peg.gol_ruang='2d', 1, null)) AS jum_peg_gol_2d,
count(if (m_peg.gol_ruang='3a', 1, null)) AS jum_peg_gol_3a,
count(if (m_peg.gol_ruang='3b', 1, null)) AS jum_peg_gol_3b,
count(if (m_peg.gol_ruang='3c', 1, null)) AS jum_peg_gol_3c,
count(if (m_peg.gol_ruang='3d', 1, null)) AS jum_peg_gol_3d,
count(if (m_peg.gol_ruang='4a', 1, null)) AS jum_peg_gol_4a,
count(if (m_peg.gol_ruang='4b', 1, null)) AS jum_peg_gol_4b,
count(if (m_peg.gol_ruang='4c', 1, null)) AS jum_peg_gol_4c,
count(if (m_peg.gol_ruang='4d', 1, null)) AS jum_peg_gol_4d,
count(if (m_peg.gol_ruang='4e', 1, null)) AS jum_peg_gol_4e,
count(if (m_peg.pend_terakhir=1, 1, null)) AS jum_peg_sd,
count(if (m_peg.pend_terakhir=2, 1, null)) AS jum_peg_smp,
count(if (m_peg.pend_terakhir=3, 1, null)) AS jum_peg_sma,
count(if (m_peg.pend_terakhir=4, 1, null)) AS jum_peg_d1,
count(if (m_peg.pend_terakhir=5, 1, null)) AS jum_peg_d2,
count(if (m_peg.pend_terakhir=6, 1, null)) AS jum_peg_d3,
count(if (m_peg.pend_terakhir=7, 1, null)) AS jum_peg_d4,
count(if (m_peg.pend_terakhir=8, 1, null)) AS jum_peg_akademi,
count(if (m_peg.pend_terakhir=9, 1, null)) AS jum_peg_akt4,
count(if (m_peg.pend_terakhir=10, 1, null)) AS jum_peg_s1,
count(if (m_peg.pend_terakhir=11, 1, null)) AS jum_peg_s2,
count(if (m_peg.pend_terakhir=12, 1, null)) AS jum_peg_s3,
count(if (m_peg.pend_terakhir=13, 1, null)) AS jum_peg_profesi,
count(if (m_peg.pend_terakhir=14, 1, null)) AS jum_peg_spesialis
FROM m_peg 
GROUP BY id_opd